Remove trailing slash from clone path
The trailing slash caused this error on few machines - 

```
git clone --depth=1 https://github.com/cleanbrowsing/dnsperftest/
Cloning into 'dnsperftest'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```